/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton'];
    ElCard: typeof import('element-plus/es')['ElCard'];
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions'];
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem'];
    ElDialog: typeof import('element-plus/es')['ElDialog'];
    ElInput: typeof import('element-plus/es')['ElInput'];
    ElTimeline: typeof import('element-plus/es')['ElTimeline'];
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem'];
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default'];
    IconLeft1: typeof import('./src/components/icons/ol-map/iconLeft1.vue')['default'];
    IconLeft2: typeof import('./src/components/icons/ol-map/iconLeft2.vue')['default'];
    IconLeft3: typeof import('./src/components/icons/ol-map/iconLeft3.vue')['default'];
    IconLeft4: typeof import('./src/components/icons/ol-map/iconLeft4.vue')['default'];
    IconSearch: typeof import('./src/components/icons/iconSearch.vue')['default'];
    IconStation: typeof import('./src/components/icons/icon-station.vue')['default'];
    JuejinApproval: typeof import('./src/components/icons/juejin-part/juejin-approval.vue')['default'];
    JuejinArrow: typeof import('./src/components/icons/juejin-part/juejin-arrow.vue')['default'];
    JuejinComment: typeof import('./src/components/icons/juejin-part/juejin-comment.vue')['default'];
    JuejinDemo: typeof import('./src/components/icons/juejin-part/juejin-demo.vue')['default'];
    JuejinMsg: typeof import('./src/components/icons/juejin-part/juejin-msg.vue')['default'];
    JuejinSearch: typeof import('./src/components/icons/juejin-part/juejin-search.vue')['default'];
    JuejinViews: typeof import('./src/components/icons/juejin-part/juejin-views.vue')['default'];
    Map: typeof import('./src/components/ol-map/map.vue')['default'];
    PathMap: typeof import('./src/components/icons/ol-map/pathMap.vue')['default'];
    PieChart: typeof import('./src/components/charts/pie-chart.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
  }
}
